
name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env: 
      CI: true
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.3.0
        with:
          node-version: 14.x
      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        env: 
          REACT_APP_API_KEY_FIREBASE: ${{ secrets.API_KEY_FIREBASE }}
          REACT_APP_AUTH_DOMAIN_FIREBASE: ${{ secrets.AUTH_DOMAIN_FIREBASE }}
          REACT_APP_PROJECT_ID_FIREBASE: ${{ secrets.PROJECT_ID_FIREBASE }}
          REACT_APP_STORAGE_BUCKET_FIREBASE: ${{ secrets.STORAGE_BUCKET_FIREBASE}}
          REACT_APP_MESSAGING_SENDERID_FIREBASE: ${{ secrets.MESSAGING_SENDERID_FIREBASE }}
          REACT_APP_APP_ID_FIREBASE: ${{ secrets.APP_ID_FIREBASE }}
        run: |
          npm install --force
          npm run build
          yarn add generate
          yarn run generate
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.9
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.
