
name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env: 
      CI: true
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
        env: 
          REACT_APP_API_KEY_FIREBASE: ${{ secrets.API_KEY_FIREBASE }}
          REACT_APP_AUTH_DOMAIN_FIREBASE: ${{ secrets.AUTH_DOMAIN_FIREBASE }}
          REACT_APP_PROJECT_ID_FIREBASE: ${{ secrets.PROJECT_ID_FIREBASE }}
          REACT_APP_STORAGE_BUCKET_FIREBASE: ${{ secrets.STORAGE_BUCKET_FIREBASE}}
          REACT_APP_MESSAGING_SENDERID_FIREBASE: ${{ secrets.MESSAGING_SENDERID_FIREBASE }}
          REACT_APP_APP_ID_FIREBASE: ${{ secrets.APP_ID_FIREBASE }}
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.9
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.
